services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: maxim
      POSTGRES_PASSWORD: Famous1507
      POSTGRES_DB: cloudFileStorage
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data: