version: '3'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: maxim
      POSTGRES_PASSWORD: Famous1507
      POSTGRES_DB: cloudFileStorage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
